# Generated by Django 3.2.19 on 2023-05-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callout_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='request',
        ),
    ]
