# Generated by Django 3.2.19 on 2023-05-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callout_request', '0003_request_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='excerpt',
            new_name='equipment',
        ),
    ]
