# Generated by Django 3.2.19 on 2023-05-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callout_request', '0004_rename_excerpt_request_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='author',
            new_name='user',
        ),
    ]
